# This file defines the build steps for Cloud Build
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/locusearch:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/locusearch:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'locusearch'
    - '--image'
    - 'gcr.io/$PROJECT_ID/locusearch:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port'
    - '8080'
    - '--memory'
    - '1Gi'
    - '--cpu'
    - '1'
    - '--max-instances'
    - '10'
    - '--min-instances'
    - '0'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/locusearch:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/locusearch:latest'

# Optional: Add timeout for the build (default is 10 minutes)
timeout: '20m'

# Optional: Add substitutions if you need to override values
options:
  logging: CLOUD_LOGGING_ONLY
  
# Optional: If you want to tag the image as latest as well
# Add this step after the push step and before deploy:
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['tag', 'gcr.io/$PROJECT_ID/locusearch:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/locusearch:latest']
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', 'gcr.io/$PROJECT_ID/locusearch:latest']