"""Added Title Value to Query

Revision ID: 86504b367109
Revises: d460638291fe
Create Date: 2025-06-14 19:56:57.599773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86504b367109'
down_revision: Union[str, None] = 'd460638291fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_authors_conn_id', table_name='authors')
    op.drop_table('authors')
    op.drop_index('ix_documents_document_id', table_name='documents')
    op.drop_index('ix_documents_subject', table_name='documents')
    op.drop_index('ix_documents_uploaded_by', table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('document_id', sa.INTEGER(), nullable=False),
    sa.Column('document_name', sa.VARCHAR(), nullable=False),
    sa.Column('document_link', sa.VARCHAR(), nullable=True),
    sa.Column('uploaded_by', sa.VARCHAR(), nullable=True),
    sa.Column('upload_date', sa.DATETIME(), nullable=True),
    sa.Column('subject', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('document_id'),
    sa.UniqueConstraint('document_link')
    )
    op.create_index('ix_documents_uploaded_by', 'documents', ['uploaded_by'], unique=False)
    op.create_index('ix_documents_subject', 'documents', ['subject'], unique=False)
    op.create_index('ix_documents_document_id', 'documents', ['document_id'], unique=False)
    op.create_table('authors',
    sa.Column('conn_id', sa.INTEGER(), nullable=False),
    sa.Column('authorname', sa.VARCHAR(), nullable=False),
    sa.Column('authoremail', sa.VARCHAR(), nullable=True),
    sa.Column('document_conn', sa.INTEGER(), nullable=True),
    sa.Column('primary_author', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['document_conn'], ['documents.document_id'], ),
    sa.PrimaryKeyConstraint('conn_id')
    )
    op.create_index('ix_authors_conn_id', 'authors', ['conn_id'], unique=1)
    # ### end Alembic commands ###
